classDiagram
  class AccountStatus {
    <<enumeration>>
    Active
    Disabled
  }
  class ContractStatus {
    <<enumeration>>
    Confirmed
    Active
    Completed
  }
  class PlanStatus {
    <<enumeration>>
    Active
    Inactive
  }
  class BillingUnit {
    <<enumeration>>
    Day
    Week
    Month
  }
